### ISSUE TITLE
[Bug]: Nim installation is too long!

### ISSUE THREAD

**Issue by Ethosa** [jiro4989/setup-nim-action#483] opened 2024-06-28 16:54 UTC
### What happened?

When gh action was run this action is do nothing(?) too long.

### Actions log url

https://github.com/HapticX/happyx/actions/runs/9716162111

and many actions before

**Comment by Ethosa** [comment] 2024-06-28 16:55
What is noteworthy is that when installing Nim without this action, it is installed quite smartly

**Comment by Ethosa** [comment] 2024-06-28 16:57
this action:
![image](https://github.com/jiro4989/setup-nim-action/assets/49402667/b0f50a4b-bd83-4a47-9998-e63d5b81b271)

without action:
![image](https://github.com/jiro4989/setup-nim-action/assets/49402667/95ac69bd-a38d-44cc-b1c1-e9f981b6e709)

**Comment by jiro4989** [comment] 2024-06-29 07:21
@Ethosa thanks. I added a temporary patch. Please try using setup-nim-action 1.5.2 or later.
The installation will be completed in about 10 seconds.

**Comment by fox0430** [comment] 2024-07-04 21:30
In my environment, Nim 1.x is fast but Nim 2.x is still slow...

1.x - about 20 seconds
2.x - about 6 minutes

https://github.com/fox0430/moe/actions/runs/9798974578/job/27061052837

Do I need aditinal configs?

**Comment by jiro4989** [comment] 2024-07-04 22:29
I'm not sure what the cause is. It's suddenly become slow even though I haven't made any changes.

Using choosenim on a job is fast, so there may be a problem with the Node runtime for GitHub Actions.

**Comment by jiro4989** [comment] 2024-07-04 22:40
I know that the installation is very slow on a Mac runner. https://github.com/jiro4989/setup-nim-action/pull/487

But no good solution has been found yet.

**Comment by jiro4989** [comment] 2024-07-05 15:40
@Ethosa @fox0430 I will be making a major change to setup-nim-action.

Until now, setup-nim-action depended on `choosenim`.
However, it seems that installing using choosenim has become very slow.
So I will change the way to install Nim without using `choosenim`.

#491 

I created a new version [`v2-beta`](https://github.com/jiro4989/setup-nim-action/releases/tag/v2-beta), and testing it now.

I tested setup-nim-action `v2-beta` on my repositories:

* https://github.com/jiro4989/nimjson/pull/44
* https://github.com/jiro4989/faker/pull/88
* https://github.com/jiro4989/envconfig/pull/6

The tests complete in under 30 seconds on Ubuntu and Windows.
The tests complete in under 6 minutes on MacOS.

This is BREAKING_CHANGES.
So I need your help.

Please re-run your CI tests with setup-nim-action `v2-beta`.

```yaml
      - uses: jiro4989/setup-nim-action@v2-beta
        with:
          nim-version: 2.0.8
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by fox0430** [comment] 2024-07-05 15:51
@jiro4989 

Thank you for a great job. So, I tried it and it seems to fail. Do you know if I need to do anything?

https://github.com/fox0430/moe/pull/2086

https://github.com/fox0430/moe/actions/runs/9810738115/job/27091529854

**Comment by jiro4989** [comment] 2024-07-05 15:53
Hmm, please try to delete cache action.

https://github.com/fox0430/moe/actions/runs/9810738115/job/27091529854#step:3:1

**Comment by fox0430** [comment] 2024-07-05 15:58
@jiro4989 

It works! Thank you! And, `devel` is not supported yet, is it?

**Comment by jiro4989** [comment] 2024-07-05 16:01
Yes, `devel` is not supported yet. I will do it soon.

**Comment by jiro4989** [comment] 2024-07-05 17:12
@fox0430 I fixed `devel` version support.
Please re-run your `setup-nim-action@v2-beta` CI.

**Comment by fox0430** [comment] 2024-07-05 17:29
@jiro4989 

Passed all and macOS and stable (2.0.8) are much faster! Thank you!

https://github.com/fox0430/moe/actions/runs/9810836173

**Comment by jiro4989** [comment] 2024-07-05 17:34
@fox0430 Thanks for your help👍
It's too late for that today so I'll release `v2` tomorrow.
And I will write `v2` documentations and migrations.

**Comment by jiro4989** [comment] 2024-07-06 01:22
@Ethosa @fox0430 v2 version released.
https://github.com/jiro4989/setup-nim-action/releases/tag/v2

Please use `jiro4989/setup-nim-action@v2`.

See: [Migration guide](https://github.com/jiro4989/setup-nim-action?tab=readme-ov-file#migration-to-v2-from-v1)

**Comment by Ethosa** [comment] 2024-07-07 06:55
@jiro4989 https://github.com/HapticX/happyx/actions/runs/9825359062/job/27125416903

`/home/runner/work/_temp/b27fe6ae-1169-4182-9847-f39343eeb675.sh: line 4: /home/runner/.nimble/bin/nim: No such file or directory`

**Comment by Ethosa** [comment] 2024-07-07 06:58
And here also:
https://github.com/HapticX/happyx/actions/runs/9825372687

**Comment by jiro4989** [comment] 2024-07-07 07:13
try using not-fullpath nim command. nim exists in PATH. ([Log](https://github.com/HapticX/happyx/actions/runs/9825359062/job/27125416903#step:4:28))

```diff
        run: |
          cd tests
          for file in $(ls -v testc*.nim); do
            echo "###===--- C Test for " $file " via HttpBeast ---===###"
-           /home/runner/.nimble/bin/nim c -d:beast -d:debug --hints:off --warnings:off $file
+           nim c -d:beast -d:debug --hints:off --warnings:off $file
          done
        shell: bash
```

And change cache key, and delete choosenim directory.

```diff
      - uses: actions/cache@v4
        with:
          path: |
            ~/.nimble
-           ~/.choosenim
-         key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
+         key: ${{ runner.os }}-nimble-v2-${{ hashFiles('*.nimble') }}
```

**Comment by Ethosa** [comment] 2024-07-07 07:35
https://github.com/HapticX/happyx/actions/runs/9825579385/job/27125918172
Hm, seems like not working

**Comment by jiro4989** [comment] 2024-07-07 07:46
It looks that you didn't call setup-nim-action in the workflow.

1. actions/checkout@v4
2. actions/cache@v4
3. **jiro4989/setup-nim-action@v2** <-- Need here
4. Build C tests

![image](https://github.com/jiro4989/setup-nim-action/assets/13825004/56ae022c-41d6-443e-9b46-6c1f8e4cce04)

**Comment by Ethosa** [comment] 2024-07-07 07:50
setup was in `dependencies` job

**Comment by jiro4989** [comment] 2024-07-07 08:03
add cache path to dependencies job.

```diff
      - uses: actions/cache@v4
        with:
          path: |
            ~/.nimble
+           .nim_runtime
          key: ${{ runner.os }}-nimble-v2-${{ hashFiles('*.nimble') }}
```

and set `PATH` to after jobs.

```diff
      - uses: actions/cache@v4
        with:
          path: |
            ~/.nimble
+           .nim_runtime
          key: ${{ runner.os }}-nimble-v2-${{ hashFiles('*.nimble') }}
      - name: Build C tests (Default HTTP Server) ⚡
        run: |
+         export PATH=$PATH:$PWD/.nim_runtime/bin
          cd tests
          echo "###===--- Default for" $file "---===###"
          for file in $(ls -v testc*.nim); do
            echo "###===--- C Test for " $file " via stdlib ---===###"
            nim c -d:debug --hints:off --warnings:off $file
          done
        shell: bash
```

**Comment by Ethosa** [comment] 2024-07-07 09:15
@jiro4989  thanks you!

**Comment by dlesnoff** [comment] 2024-07-08 08:39
The checks are failing in my repository for the v2 upgrade:
```raw
Run jiro4989/setup-nim-action@v2
Run "/home/runner/work/_actions/jiro4989/setup-nim-action/v2/install_nim.sh" \
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   109  100   109    0     0   1037      0 --:--:-- --:--:-- --:--:--  1038
jq: error (at <stdin>:5): Cannot index string with string "ref"
Mon Jul  8 05:02:48 UTC 2024 [INFO] install nim 
tar: This does not look like a tar archive
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: Process completed with exit code 2.
```
Are similar changes as those recommended to Ethosa necessary for this upgrade?

**Comment by vil02** [comment] 2024-07-08 10:16
@dlesnoff: when `nim-version` is set to `stable` (i.e. its [default value](https://github.com/jiro4989/setup-nim-action/blob/9bf991d1d73ca3b46766c6cb6d2ff5872b1b47b1/action.yml#L11)), then the [`download_url`](https://github.com/jiro4989/setup-nim-action/blob/9bf991d1d73ca3b46766c6cb6d2ff5872b1b47b1/install_nim.sh#L118) becomes `https://nim-lang.org/download/nim-stable-linux_x64.tar.xz`, which does not lead to an existing file.

**Comment by jiro4989** [comment] 2024-07-08 10:41
@dlesnoff Did you set a `repo-token` parameter?

```diff
  - uses: jiro4989/setup-nim-action@v2
    with:
      nim-version: '2.0.0' # default is 'stable'
+     repo-token: ${{ secrets.GITHUB_TOKEN }}
```

`repo-token` is using for [Rate limiting](https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting).

> jq: error (at <stdin>:5): Cannot index string with string "ref"

I think that [GitHub API](https://github.com/jiro4989/setup-nim-action/blob/9bf991d1d73ca3b46766c6cb6d2ff5872b1b47b1/install_nim.sh#L7-L10) reached Rate limit.

**Comment by jiro4989** [comment] 2024-07-08 11:34
@dlesnoff `stable` bug was fixed ( https://github.com/jiro4989/setup-nim-action/pull/497 ).
Please re-run `setup-nim-action@v2`.

**Comment by dlesnoff** [comment] 2024-07-08 13:31
It works but I have to change all potentially destructive instructions to exclude the .nim_runtime directory. Destructive instructions being nim prettyfy or git clean.

Wasn't it possible to put the nim directory in another separate temporary directory like runner.temp (is it writable?, see: https://github.com/actions/toolkit/issues/518).

**Comment by jiro4989** [comment] 2024-07-08 13:43
You can use `nim-install-directory` if you want to change nim directory.

```diff
  - uses: jiro4989/setup-nim-action@v2
    with:
      nim-version: '2.0.0' # default is 'stable'
      repo-token: ${{ secrets.GITHUB_TOKEN }}
+     nim-install-directory: ${{ runner.temp }}
```

**Comment by dlesnoff** [comment] 2024-07-08 13:44
Thanks!
I'll try that!

**Comment by jiro4989** [comment] 2024-07-08 13:53
If `${{ runner.temp }}` fails, try `${{ runner.temp }}/nim_runtime` too.

**Comment by dlesnoff** [comment] 2024-07-08 13:57
It fails. Shouldn't these lines use the nim-install-directory variable ?
```sh
  echo "$PWD//home/runner/work/_temp/bin" >> "$GITHUB_PATH"
  echo "$HOME/.nimble/bin" >> "$GITHUB_PATH"
```

**Comment by jiro4989** [comment] 2024-07-08 14:09
OMG, this is bug. I will fix it🙇

**Comment by jiro4989** [comment] 2024-07-08 16:25
@dlesnoff Added `parent-nim-install-directory` parameter.
We can change install destination directory.

```diff
  - uses: jiro4989/setup-nim-action@v2
    with:
      nim-version: '2.0.0' # default is 'stable'
      repo-token: ${{ secrets.GITHUB_TOKEN }}
+     parent-nim-install-directory: ${{ runner.temp }}
```

This example installs nim to `/home/runner/work/_temp/.nim_runtime`.

**Comment by dlesnoff** [comment] 2024-07-08 17:18
Still not there!
When re-running job, nim full path is not there! https://github.com/TheAlgorithms/Nim/actions/runs/9840934507/job/27176546752#step:3:38

**Comment by jiro4989** [comment] 2024-07-09 00:36
@dlesnoff Did you solve?

https://github.com/jiro4989/setup-nim-action/issues/499#issuecomment-2215176648

The issues are getting long, so I would like to close them soon.

**Comment by dlesnoff** [comment] 2024-07-09 08:11
You can close it. It was an error on my side sorry.
I did not notice that you changed nim-install-directory to parent-nim-install-directory.

**Comment by jiro4989** [comment] 2024-07-09 10:11
OK. The slow installation issue has been resolved, so I will close this issue.

Please open a new issue if anyone find any issues with `v2` version.

**Closed** 2024-07-09 10:12 UTC
Labels: bug
